# Bu dosyada Prometheus'un tüm scrape ayarlarını tutuyorum.
# Target listelerini elle yazmak yerine, Terraform output'lardan
# otomatik dolduran bir script kullanıyorum.
# Aşağıdaki AUTO-START/END bloklarını script dolduruyor.


global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:

  # =======================
  # Node Exporter
  # =======================
  # AUTO-NODE-EXPORTER-START
  - job_name: "node_exporter"
    static_configs:
      - targets: []
  # AUTO-NODE-EXPORTER-END

  # =======================
  # Kafka Broker JMX
  # =======================
  # AUTO-BROKER-JMX-START
  - job_name: "kafka_broker_jmx"
    static_configs:
      - targets: []
  # AUTO-BROKER-JMX-END

  # =======================
  # Kafka Controller JMX
  # =======================
  # AUTO-CONTROLLER-JMX-START
  - job_name: "kafka_controller_jmx"
    static_configs:
      - targets: []
  # AUTO-CONTROLLER-JMX-END

  # =======================
  # Kafka Connect JMX
  # =======================
  # AUTO-CONNECT-JMX-START
  - job_name: "connect_jmx"
    static_configs:
      - targets: []
  # AUTO-CONNECT-JMX-END
