# Bu dosyada Prometheus'un tüm scrape ayarlarını tutuyorum.

global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "192.168.56.10:9100"
          - "192.168.56.11:9100"
          - "192.168.56.12:9100"
          - "192.168.56.13:9100"
          - "192.168.56.30:9100"
          - "192.168.56.31:9100"
          - "192.168.56.32:9100"
          - "192.168.56.50:9100"
          - "192.168.56.60:9100"

  - job_name: "kafka_broker_jmx"
    static_configs:
      - targets:
          - "192.168.56.10:5555"
          - "192.168.56.11:5555"
          - "192.168.56.12:5555"
          - "192.168.56.13:5555"

  - job_name: "kafka_controller_jmx"
    static_configs:
      - targets:
          - "192.168.56.30:5556"
          - "192.168.56.31:5556"
          - "192.168.56.32:5556"

  - job_name: "connect_jmx"
    static_configs:
      - targets:
          - "192.168.56.50:7777"
          - "192.168.56.50:7778"
