global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:

  # =======================
  # Node Exporter
  # =======================
  # AUTO-NODE-EXPORTER-START
  # targets will be inserted here
  # AUTO-NODE-EXPORTER-END

  # =======================
  # Kafka Broker JMX
  # =======================
  # AUTO-BROKER-JMX-START
  # targets will be inserted here
  # AUTO-BROKER-JMX-END

  # =======================
  # Kafka Controller JMX
  # =======================
  # AUTO-CONTROLLER-JMX-START
  # targets will be inserted here
  # AUTO-CONTROLLER-JMX-END

  # =======================
  # Kafka Connect JMX
  # =======================
  # AUTO-CONNECT-JMX-START
  # targets will be inserted here
  # AUTO-CONNECT-JMX-END
